docs/Engineering/Misc/reading-list.md

Move the page, remove the silly sub-catagory name

---

docs/Engineering/Misc/reading-list.md

Signed-off-by: ChrisScottThomas <chris.scott-thomas@burendo.com>

Add blog Why T-Shaped People

---

docs/Engineering/Misc/reading-list.md

Signed-off-by: ChrisScottThomas <chris.scott-thomas@burendo.com>

Not rendering correctly in Docusaurus

---

docs/Engineering/man.md

Fix spelling

---

docs/Engineering/engineering-practice.md
docs/intro.md

Signed-off-by: ChrisScottThomas <chris.scott-thomas@burendo.com>

Rename to Engineering handbook...for now

---

docs/Engineering/Procedures/CI.md

Creating a new entry for Continuous Integration

---

README.md

- Update README to include using GitHub IDE for adding content.

update README no screenshots

---

docs/Engineering/Labs/beginners-lab.md
docs/Engineering/Labs/our-learnings.md

Fix page structure - Make learnings a cleaner split

---

docs/Engineering/Labs/our-learnings.md

Fix our-learnings page link

---

.github/workflows/merge.yml

Automatically fire infra rebuild & deploy on merge to main

---

docs/People/Roles/full-stack-engineer.md
docs/People/Roles/test-consultant.md

Edited wording to ensure we are as inclusive as possible in our job descriptions.

Gender neutral job description

---

.github/workflows/merge.yml

Fix path wildcard

---

docs/Engineering/Labs/beginners-lab.md

Update labs available to be a list

---

docs/intro.md

Signed-off-by: ChrisScottThomas <chris.scott-thomas@burendo.com>

Fix naming - no longer just Engineering

---

docs/intro.md

Just in case there is any confusion, I've added a line to ensure this is not confusing for people when they read their contracts.

Add context in regards to staff handbook

---

blog/2023-03-20-Test-blog.md

First blog

---

blog/authors.yml

Add authors

---

blog/2023-03-20-Test-blog.md
blog/authors.yml

Complete first blog

---

.github/workflows/merge.yml
blog/2023-03-20-Test-blog.md

Trigger infra build on blog updates

Trigger infra build on blog updates

---

docs/contribute.md

Fix case issue with images

---

docs/static-menu/logout.md

Add logout page

---

docs/static-menu/logout.md

Fix link on logout page

---

docs/autogenerated-menu/Our People/off client/FAQs.md
docs/autogenerated-menu/Our People/off client/Info.md
docs/autogenerated-menu/Our People/off client/Introduction.md
docs/static-menu/contribute.md

New folder and two new pages created with light touch info covering OC info and faqs

OC information

---

docs/static-menu/intro.md

Home page typo

---

docs/static-menu/intro.md

Update the home page description to be explicit about the Handbook's place within Burendo

Update home page

---

docs/static-menu/intro.md

Fix header on home page

---

blog/2023-06-16-Future-tech-trends.md

Blog with future tech trends to promote our AWS Summit attendance.

Blog with future tech trends

---

blog/2023-03-20-Test-blog.md

Revisit intro blog to not mention private content

Revisit intro blog to not mention private content

---

docs/static-menu/contribute.md

Rework the contribution guide to have a much better flow from feedback from first non-engineer using it

Rework the contribution guide to have a much better flow

---

docs/static-menu/contribute.md

Fix image link

---

blog/authors.yml
docs/static-menu/contribute.md

Fix small author file spacing issues and update contribution guide with Paddy's suggestions

Fix small author file spacing issues and update contribution guide

---

blog/2023-07-13-The-Maths-Behind-the-Curt(ai)n.md

Add truncate and remove slack emoji syntax

Add truncate and remove slack emoji syntax

---

docs/static-menu/contribute.md

Notes to perform the common actions first

Notes to perform the common actions first

---

blog/authors.yml

Fix indentation in author file

Fix indentation in author file

---

docs/static-menu/contribute.md

Add author note about indentation

Add author note about indentation

---

blog/authors.yml

* LinkedIn was missing https://
* authors pic was jpg not png

Fix authors file

---

blog/2023-08-08-make-it-date-it.md
blog/authors.yml

Adding the blog - If you don't make it don't date it.

Adding Warran's Blog

---

blog/2023-08-20-Engineers-playbook-handling-incidents.md

Add description to Connor's blog

Add description to Connor's blog

---

docs/autogenerated-menu/Our People/Off Client Support/The OC.md

As per title, discussion with Steven W as CDL for OC, and in relation to OC request to update handbook to reflect current practice.
Wording in line with the intent and sponsorship of the OC by Helen, but any wording amendments welcome. 
The image whilst good for how things were, probably isn't how things are now

Update to the content of the OC page for external viewers

---

docs/autogenerated-menu/Our People/Off Client Support/The OC.md

Update to the content of the OC page for external viewers (#115)

Update to the content of the OC page for external viewers (#115)

---

docs/autogenerated-menu/Our Practices/Engineering/man.md

- Better wording from lessons learned over time.
- Includes security considerations.

Update Engineering Manfesto.  

---

.pages.yml
docs/autogenerated-menu/Our Practices/Engineering/Procedures/Document Demonstrate Duplicate.md

PagesCMS broke after an update.  
* Fixed DDD doc that was missing required fields.
* Added media to config and fixed relevant areas to use new config.
Pages now render for editing and both media repositories work separately.

Pagescms bug 100425
